import { AdvertDataType } from '../Components/AdvertPreview/AdvertPreview/AdvertPreview';

export const advertData = [
  {
    id: '1',
    title: 'Advert',
    photo: 'https://kursors.lv/wp-content/uploads/2019/09/2020-porsche-taycan.jpg',
    year: '2020',
    isElectric: true,
    isInTrending: true,
    price: '223 000 $',
  },
  {
    id: '1',
    title: 'Advert',
    photo: 'https://kursors.lv/wp-content/uploads/2019/09/2020-porsche-taycan.jpg',
    year: '2020',
    isElectric: true,
    isInTrending: true,
    price: '223 000 $',
  },
  {
    id: '1',
    title: 'Advert',
    photo: 'https://kursors.lv/wp-content/uploads/2019/09/2020-porsche-taycan.jpg',
    year: '2020',
    isElectric: true,
    isInTrending: true,
    price: '223 000 $',
  },
] as AdvertDataType[];

export const biggerAdvertData = [
  {
    id: '1',
    title: 'Advert',
    photo: 'https://kursors.lv/wp-content/uploads/2019/09/2020-porsche-taycan.jpg',
    year: '2020',
    isElectric: true,
    isInTrending: true,
    price: '223 000 $',
  },
  {
    id: '1',
    title: 'Advert',
    photo: 'https://kursors.lv/wp-content/uploads/2019/09/2020-porsche-taycan.jpg',
    year: '2020',
    isElectric: true,
    isInTrending: true,
    price: '223 000 $',
  },
  {
    id: '1',
    title: 'Advert',
    photo: 'https://kursors.lv/wp-content/uploads/2019/09/2020-porsche-taycan.jpg',
    year: '2020',
    isElectric: true,
    isInTrending: true,
    price: '223 000 $',
  },
  {
    id: '1',
    title: 'Advert',
    photo: 'https://kursors.lv/wp-content/uploads/2019/09/2020-porsche-taycan.jpg',
    year: '2020',
    isElectric: true,
    isInTrending: true,
    price: '223 000 $',
  },
  {
    id: '1',
    title: 'Advert',
    photo: 'https://kursors.lv/wp-content/uploads/2019/09/2020-porsche-taycan.jpg',
    year: '2020',
    isElectric: true,
    isInTrending: true,
    price: '223 000 $',
  },
  {
    id: '1',
    title: 'Advert',
    photo: 'https://kursors.lv/wp-content/uploads/2019/09/2020-porsche-taycan.jpg',
    year: '2020',
    isElectric: true,
    isInTrending: true,
    price: '223 000 $',
  },
] as AdvertDataType[];
